# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20160124_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='end_time',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
