# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20160128_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='start_time',
        ),
    ]
